apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-image-renderer
  name: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
      - name: grafana-image-renderer
        image: asksven/grafana-image-renderer:1
        env:
#        - name: HTTP_HOST
#          value: "localhost"
        - name: HTTP_PORT
          value: "8081"
        - name: BROWSER_TZ
          value: "Europe/Berlin"
        - name: IGNORE_HTTPS_ERRORS
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "debug" # error, warning, info
        - name: RENDERING_VERBOSE_LOGGING
          value: "true"
        - name: RENDERING_DUMPIO
          value: "true"
        - name: RENDERING_ARGS
          value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758"
        - name: RENDERING_MODE
          value: "default"
        ports:
        - name: http
          containerPort: 8081

